# Uncomment the next line to define a global platform for your project
platform :ios, '13.1'

target 'marsianStrawberry' do
  # Comment the next line if you don't want to use dynamic frameworks
 use_frameworks!

  # Pods for marsianStrawberry
  pod 'PNChart'
end
